# Generated by Django 2.2.3 on 2019-07-11 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_auto_20190711_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
