# Generated by Django 2.2.3 on 2019-07-11 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noteapp', '0003_auto_20190711_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='labels_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='delete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
